apiVersion: apps/v1
kind: Deployment
metadata:
  name: acm-kessel-inventory-api
  namespace: acm-kessel
  labels:
    app: acm-kessel-inventory-api
    app.kubernetes.io/name: inventory-api
    app.kubernetes.io/component: kessel
    app.kubernetes.io/part-of: acm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acm-kessel-inventory-api
  template:
    metadata:
      labels:
        app: acm-kessel-inventory-api
    spec:
      initContainers:
      - name: migration
        image: quay.io/redhat-services-prod/project-kessel-tenant/kessel-inventory/inventory-api:f2a8a16
        command: ["inventory-api", "migrate"]
        env:
        - name: INVENTORY_API_CONFIG
          value: "/inventory/inventory-api-config.yaml"
        - name: INVENTORY_API_STORAGE_POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: acm-kessel-postgres-pguser-inventory-api
              key: host
        - name: INVENTORY_API_STORAGE_POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: acm-kessel-postgres-pguser-inventory-api
              key: port
        - name: INVENTORY_API_STORAGE_POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: acm-kessel-postgres-pguser-inventory-api
              key: user
        - name: INVENTORY_API_STORAGE_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: acm-kessel-postgres-pguser-inventory-api
              key: password
        - name: INVENTORY_API_STORAGE_POSTGRES_DBNAME
          valueFrom:
            secretKeyRef:
              name: acm-kessel-postgres-pguser-inventory-api
              key: dbname
        volumeMounts:
        - name: config-volume
          mountPath: /inventory
          readOnly: true
      containers:
      - name: inventory-api
        image: quay.io/redhat-services-prod/project-kessel-tenant/kessel-inventory/inventory-api:f2a8a16
        command: ["inventory-api", "serve"]
        ports:
        - name: grpc
          containerPort: 9000
          protocol: TCP
        env:
        - name: INVENTORY_API_CONFIG
          value: "/inventory/inventory-api-config.yaml"
        - name: RESOURCE_DIR
          value: "/data/schema/resources"
        - name: INVENTORY_API_AUTHZ_KESSEL_URL
          value: "acm-kessel-relations-api.acm-kessel.svc.cluster.local:9000"
        - name: INVENTORY_API_STORAGE_POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: acm-kessel-postgres-pguser-inventory-api
              key: host
        - name: INVENTORY_API_STORAGE_POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: acm-kessel-postgres-pguser-inventory-api
              key: port
        - name: INVENTORY_API_STORAGE_POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: acm-kessel-postgres-pguser-inventory-api
              key: user
        - name: INVENTORY_API_STORAGE_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: acm-kessel-postgres-pguser-inventory-api
              key: password
        - name: INVENTORY_API_STORAGE_POSTGRES_DBNAME
          valueFrom:
            secretKeyRef:
              name: acm-kessel-postgres-pguser-inventory-api
              key: dbname
        volumeMounts:
        - name: config-volume
          mountPath: /inventory
          readOnly: true
        - name: schema-cache
          mountPath: /schema_cache.json
          subPath: schema_cache.json
          readOnly: true
        livenessProbe:
          httpGet:
            path: /api/inventory/v1/livez
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/inventory/v1/readyz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: config-volume
        secret:
          secretName: acm-kessel-inventory-api-config
      - name: schema-cache
        configMap:
          name: acm-kessel-schema-cache
