server:
  public_url: http://0.0.0.0:8000
  http:
    address: 0.0.0.0:8000
  grpc:
    address: 0.0.0.0:9000
  pprof:
    enabled: true
authn:
  allow-unauthenticated: true
authz:
  impl: kessel
  kessel:
    insecure-client: true
    # url is set as an env
    enable-oidc-auth: false
eventing:
  eventer: stdout # configure to use kafka
storage:
  max-serialization-retries: 10
  database: postgres
  postgres: {} # postgres params set as env
service:
  use_v1beta2_db: true
resources:
  use_cache: true
consumer:
  enabled: false # Review what this does
log:
  level: "info"
  livez: true
  readyz: true
